name: mlops-env
channels:
  - defaults #USAR ANTES: Evita conflitos de builds entre canais
  - conda-forge
dependencies:
  # Python e ferramentas básicas
  - python=3.10.18 #3.12 estava causando problemas: ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
  - pip
  - git
  - curl

  # Pacotes científicos via conda (melhor performance)
  #- numpy=1.26.4
  #- pandas=2.2.3
  #- matplotlib=3.9.2
  #- scikit-learn=1.7.0
  #- mlflow=2.9.2 # Solving environment: failed ResolvePackageNotFound: - mlflow==3.3.1

  # Jupyter para desenvolvimento
  #- jupyter
  #- jupyterlab

  # Pacotes pip específicos
  - pip:
      #forçando atualizacao do pip
      - pip>=25.2
      - setuptools>=80.9.0
      - wheel
      #instalando pacotes do requirements.txt
      - -r requirements.txt
      # Pacotes científicos via pip
      # - mlflow==3.3.1
      #- fastapi==0.116.1
      #- scikit-learn==1.7.1
      #- pandas==2.3.2
      #- matplotlib==3.10.5